
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://services/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://services/", className = "proxy.GetCompteResponse")
    @Action(input = "http://services/BanqueWS/getCompteRequest", output = "http://services/BanqueWS/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertEuroToDh", targetNamespace = "http://services/", className = "proxy.ConvertEuroToDh")
    @ResponseWrapper(localName = "convertEuroToDhResponse", targetNamespace = "http://services/", className = "proxy.ConvertEuroToDhResponse")
    @Action(input = "http://services/BanqueWS/convertEuroToDhRequest", output = "http://services/BanqueWS/convertEuroToDhResponse")
    public double convertEuroToDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompteList", targetNamespace = "http://services/", className = "proxy.GetCompteList")
    @ResponseWrapper(localName = "getCompteListResponse", targetNamespace = "http://services/", className = "proxy.GetCompteListResponse")
    @Action(input = "http://services/BanqueWS/getCompteListRequest", output = "http://services/BanqueWS/getCompteListResponse")
    public List<Compte> getCompteList();

}
